# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # set env
    env:
      GODOT_ARCHIVE_URL: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_mono_linux_x86_64.zip
      GODOT_ARCHIVE_NAME: Godot_v4.2.2-stable_mono_linux_x86_64
      GODOT_EXECUTABLE_NAME: Godot_v4.2.2-stable_mono_linux.x86_64
      GODOT_TEMPLATES_URL: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_mono_export_templates.tpz
      GODOT_TEMPLATES_FILE: Godot_v4.2.2-stable_mono_export_templates.tpz
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Godot
        run: wget $GODOT_ARCHIVE_URL

      - name: Unzip Godot
        run: unzip $GODOT_ARCHIVE_NAME.zip

      - name: Run Godot Version
        run: $GODOT_ARCHIVE_NAME/$GODOT_EXECUTABLE_NAME --version

      - name: Download Godot Templates
        run: wget $GODOT_TEMPLATES_URL

      - name: LS
        run: ls -lah
